unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on

#This is for resizing the windows
set -g allow-rename on
set -g aggressive-resize on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R



#Vim like copy paste
setw -g mode-keys vi


bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
